[tox]
envlist=py27,py3

[testenv]
setenv=
    RPMDYN_HOOK=0

[testenv:py3]
usedevelop=true

deps=
    -rrequirements.in
    pytest
    pytest-cov
    rpm-py-installer

commands=py.test -v --cov src --cov-report html .


[testenv:py27]
deps=
    -rrequirements.in
    pytest
    pytest-cov

commands=py.test -v .

setenv=
    RPMDYN_HOOK=0
    ALLOW_MISSING_NATIVE=1
