[tox]
envlist=py27,py3

[testenv]
# To use OS's rpm python bindings where available
sitepackages=true

deps=
    -rrequirements.in
    pytest
    pytest-cov

commands=py.test -v --cov src --cov-report html .
