#!/usr/bin/python3

import rpm

print("# This file was generated by scripts/gen-constants.py")
print("")

all_syms = []

for sym in sorted(dir(rpm)):
    if sym.upper() != sym:
        continue

    value = getattr(rpm, sym)
    if not isinstance(value, (int, str)):
        continue

    print("%s = %s" % (sym, repr(value)))
    all_syms.append(sym)

print("")
print("__all__ =", repr(all_syms))
